name: btc
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.3.3
  icons_plus: ^5.0.0
  http: ^1.2.2
  chart_sparkline: ^1.1.1
  web_socket_channel: ^3.0.1
  intl: ^0.19.0
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.2.1
  fl_chart: ^0.69.2
  syncfusion_flutter_charts: ^27.2.5
  chat_gpt_sdk: ^3.1.3
  dash_chat_2: ^0.0.21
  uuid: ^4.5.1
  loading_animation_widget: ^1.3.0
  currency_text_input_formatter: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - .env
